### PR TITLE
update ladda to 0.9.7 and build a gem on rubygems.org

### PR DESCRIPTION
**Pull request by Wangjiaji007**
I have forked that cause I am in a hurry to build a gem on rubygems.org

And I have updated the ladda version to 0.9.7

### CODE REVIEW

**Comment by MGPalmer** [comment]
Awesome !

**Comment by MGPalmer** [comment]
Hey Wangjiaji007, thanks for the pull request (and sorry for not merging earlier, I was afk).

Would you be interested in helping with maintaining this project ? I'm afraid I'm usually lagging behind, since I don't actually use Ladda at the moment.

**Comment by Wangjiaji007** [comment]
I am happy to maintain the project if you allow me commit on master. Cheers mate

**Comment by MGPalmer** [comment]
Alright, the ownership/team settings are a little confusing here but I think you should have full access now. Thanks for your contributions, appreciated !

**Pull request merged**
